#define MAINPREFIX z
#define PREFIX fjb_323

#include "script_version.hpp"

#define VERSION MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR MAJOR,MINOR,PATCHLVL,BUILD

#define REQUIREDVERSION 1.0
#define REQUIRED_ACE_VERSION {3,13,0}

#ifdef COMPONENT_BEAUTIFIED
  #define COMPONENT_NAME QUOTE(fjb_323 - COMPONENT_BEAUTIFIED)
#else
  #define COMPONENT_NAME QUOTE(fjb_323 - COMPONENT)
#endif
